services:
  postgres:
    image: 'postgres:alpine3.19'
    container_name: optech-postgresql
    env_file:
      - .env
    environment:
      - 'POSTGRES_USER=${DATABASE_USER}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_DB=${DATABASE_NAME}'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - default
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} -h localhost -p
          5432
      start_period: 5s
      interval: 10s
      timeout: 5s
  pg_admin:
    image: dpage/pgadmin4:8
    container_name: optech-pgadmin
    env_file:
      - .env
    environment:
      - 'PGADMIN_DEFAULT_EMAIL: optech@pgadmin.com'
      - 'PGADMIN_DEFAULT_PASSWORD: admin'
      - 'PGADMIN_CONFIG_SERVER_MODE: ''False'''
    volumes:
      - 'pgadmin:/var/lib/pgadmin'
    ports:
      - '5050:80'
    networks:
      - default
networks:
  default:
    name: optech-network
    driver: bridge
volumes:
  postgres:
    name: optech-postgresql
  pgadmin:
    name: optech-pg_admin
  chromadb:
    name: chatbot-chromadb
